# Generated by Django 5.2.7 on 2025-11-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('quantity_in_stock', models.IntegerField()),
                ('reorder_point', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
    ]
