# Generated by Django 5.2.7 on 2025-12-03 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_List', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
