# Generated by Django 5.2.7 on 2026-03-18 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_List', '0003_review_wishlistitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
