# Generated by Django 5.2.7 on 2026-03-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product_List', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
