# Generated by Django 5.2.7 on 2026-03-18 15:44

import Product_List.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product_List', '0005_product_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specs',
            field=Product_List.models.SafeJSONField(blank=True, null=True),
        ),
    ]
